############################################################################
#                                                        
#                  Spatial Sellke model - initialize a set of simulations                                 
#                  Create matrices for Q , T inf, V and P                    
#                                                        
#                  Author:   Egil Fischer                            
#                  Contact:                              
#                  Creation date                         
###########################################################################
#libraries
source("./src/loadLibraries.R")


# Set input point pattern
matrix_points <- spatial.input[,c("Xkm","Ykm")] # I select one point pattern as example
totpoints <- nrow(matrix_points) # total number of points
colnames(matrix_points) <- c("xcoord","ycoord")
# Add a column for the index
Index_points <- c(1:totpoints)
# Calculate the matrix of distances between points
# Express the coordinates as complex numbers for fast calculation of the euclidean distance
Coord <-
  (complex(length.out=2,real=matrix_points$xcoord,imaginary=matrix_points$ycoord));
distancematrix <- as.matrix(abs(outer(Coord,Coord,"-")))

#define a matrix for preemptive culling
cullingmatrix <- 1*(distancematrix<= culling.radius) #(times one keeps the matrix as it is and transforms boolean to numeric)
diag(cullingmatrix) <- matrix(0,nrow=totpoints); #no culling because of detection by itself

# Create an hazard matrix evaluating for each host j the chance to be infected by host i as a function of distance
hazardmatrix <- as.matrix(apply(distancematrix,MARGIN=c(1,2),FUN=h_kernel));
#discount hazard by vaccination
diag(hazardmatrix) <- matrix(0,nrow=totpoints); # because the chance of infecting itself is 0

# the matrices of Tinf and Qinit have been generated by the following code. 
numsim <-max.runs
totpoints <- nrow(spatial.input)
Q_init_matrix <- matrix(0,nrow=numsim,ncol=totpoints)
T_inf_matrix <- matrix(0,nrow=numsim,ncol=totpoints)
V_stat_matrix <- matrix(0,nrow=numsim,ncol=totpoints)
P_maj_matrix <- matrix(0,nrow=numsim,ncol=totpoints)

for (ii in 1:numsim){
  Q_init_matrix[ii,] <- rexp(totpoints, rate = 1)
  #vaccination status
  V_stat_matrix[ii,]<- sapply(spatial.input$TYPE,vac.func)
  #infectious period is determined by the vaccination status
  T_inf_matrix[ii,] <- mapply(Tdist, vacstat = V_stat_matrix[ii,], type = spatial.input$TYPE)
  #probability of major outbreak
  P_maj_matrix[ii,] <- sapply( V_stat_matrix[ii,], function(p){pmajor(param.list.baseline.layer, p,10)$pmajor})
}

#check with distributions fitted to simulations
# ggplot()+
#   geom_point(data= data.frame(Tinf = T_inf_matrix[1,], Vac = V_stat_matrix[1,]),aes(Vac,Tinf))+
#   geom_path(aes(x = dists$vac/100, y = dists$mean), color = "red", linewidth = 2)+
#   geom_path(aes(x = dists$vac/100, y = dists$mean-1.96*sqrt(dists$var)), color = "red", linewidth = 2)+
#   geom_path(aes(x = dists$vac/100, y = dists$mean+1.96*sqrt(dists$var)), color = "red", linewidth = 2)
