############################################################################
#                                                        
#                  Spatial Sellke model - initialize a set of simulations                                 
#                  Create matrices for Q , T inf, V and P                    
#                                                        
#                  Author:   Egil Fischer                            
#                  Contact:                              
#                  Creation date                         
###########################################################################


#load spatial input
spatial.input<- read_excel("./input/20230404_AI_AnimalLocations_SizeType_v02.xlsx", sheet = 2)

#scale coordinates to km
spatial.input$X <- spatial.input$X/1000
spatial.input$Y <- spatial.input$Y/1000
spatial.input$nr <- c(1:nrow(spatial.input))

#function to set the infectious period distribution depending on the vaccination status
Tdist = function(vacstat){
  shape = 14.5; rate = 1.2;
  if(vacstat<=0.9){shape = 14; rate = 1.2;}
  if(vacstat<=0.3){shape = 49; rate = 5.0;}
  if(vacstat<=0.02){shape = 192; rate = 23;}
  return(rgamma(1, shape= shape, rate = rate))
}


# the matrices of Tinf and Qinit have been generated by the following code. 
numsim <-10
totpoints <- nrow(spatial.input)
Q_init_matrix <- matrix(0,nrow=numsim,ncol=totpoints)
T_inf_matrix <- matrix(0,nrow=numsim,ncol=totpoints)
V_stat_matrix <- matrix(0,nrow=numsim,ncol=totpoints)
P_maj_matrix <- matrix(0,nrow=numsim,ncol=totpoints)

for (ii in 1:numsim){
  Q_init_matrix[ii,] <- rexp(totpoints, rate = 1)
  #vaccination status
  V_stat_matrix[ii,]<- sapply(spatial.input$TYPE,function(x){ifelse(x == "LAYER",runif(1),0)})
  #infectious period is determined by the vaccination status
  T_inf_matrix[ii,] <- sapply( V_stat_matrix[ii,], Tdist)
  #probability of major outbreak
  P_maj_matrix[ii,] <- sapply( V_stat_matrix[ii,], function(p){pmajor(param.list.baseline.layer, p,10)$pmajor})
}